### ISSUE TITLE
Illuminate\Database\QueryException in artisan migrate --force

### ISSUE THREAD

**Issue by chrysanthos** [dodekatheon/zeus#45]
## Error in farmakeia.com.cy

**Illuminate\Database\QueryException** in **artisan migrate --force**
could not find driver (SQL: select * from information_schema.tables where table_schema = luxastru_farmakeia and table_name = migrations and table_type = 'BASE TABLE')

[View on Bugsnag](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/611626a48e006f0007fd227e?event_id=611626a4007f923ee2f10000&i=gh&m=ci)

## Stacktrace

    vendor/laravel/framework/src/Illuminate/Database/Connection.php:678 - Illuminate\Database\Connection::runQueryCallback

[View full stacktrace](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/611626a48e006f0007fd227e?event_id=611626a4007f923ee2f10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gregkos** [comment]
PHP upgrade mishaps
