### ISSUE TITLE
Illuminate\Database\QueryException in artisan migrate --force

### ISSUE THREAD

**Issue by chrysanthos** [dodekatheon/zeus#46]
## Error in farmakeia.com.cy

**Illuminate\Database\QueryException** in **artisan migrate --force**
could not find driver (SQL: select * from information_schema.tables where table_schema = luxastru_farmakeia and table_name = migrations and table_type = 'BASE TABLE')

[View on Bugsnag](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/6116297a40b90d0007f4ec48?event_id=6116297a007f9b1ee5d70000&i=gh&m=ci)

## Stacktrace

    vendor/laravel/framework/src/Illuminate/Database/Connection.php:692 - Illuminate\Database\Connection::runQueryCallback

[View full stacktrace](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/6116297a40b90d0007f4ec48?event_id=6116297a007f9b1ee5d70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gregkos** [comment]
PHP upgrade mishaps
