### ISSUE TITLE
Symfony\Component\Console\Exception\CommandNotFoundException in artisan pharmacies:post-availability

### ISSUE THREAD

**Issue by chrysanthos** [dodekatheon/zeus#47]
## Error in farmakeia.com.cy

**Symfony\Component\Console\Exception\CommandNotFoundException** in **artisan pharmacies:post-availability**
Command "pharmacies:post-availability" is not defined.

Did you mean one of these?
    pharmacies:fill-coordinates
    pharmacies:post-available
    pharmacies:update-availability

[View on Bugsnag](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/61162bc3ab8ac80007defc69?event_id=61162bc3007f8cfe5a900000&i=gh&m=ci)

## Stacktrace

    vendor/symfony/console/Application.php:682 - Symfony\Component\Console\Application::find

[View full stacktrace](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/61162bc3ab8ac80007defc69?event_id=61162bc3007f8cfe5a900000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gregkos** [comment]
This was a typo for crying out loud.
