### ISSUE TITLE
TypeError in artisan pharmacies:post-available

### ISSUE THREAD

**Issue by chrysanthos** [dodekatheon/zeus#48]
## Error in farmakeia.com.cy

**TypeError** in **artisan pharmacies:post-available**
Cannot assign null to property App\Services\Facebook::$access_token of type string

[View on Bugsnag](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/61162bd0c21e37000729237d?event_id=61162bd0007f86d2d2370000&i=gh&m=ci)

## Stacktrace

    app/Services/Facebook.php:12 - App\Services\Facebook::__construct
    app/Console/Commands/PostAvailablePharmacies.php:64 - App\Console\Commands\PostAvailablePharmacies::handle

[View full stacktrace](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/61162bd0c21e37000729237d?event_id=61162bd0007f86d2d2370000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gregkos** [comment]
Needed to rerun optimize after changing env
