### ISSUE TITLE
GuzzleHttp\Exception\InvalidArgumentException in artisan pharmacies:post-available

### ISSUE THREAD

**Issue by chrysanthos** [dodekatheon/zeus#49]
## Error in farmakeia.com.cy

**GuzzleHttp\Exception\InvalidArgumentException** in **artisan pharmacies:post-available**
json_encode error: Malformed UTF-8 characters, possibly incorrectly encoded

[View on Bugsnag](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/61162bdea96a420007288215?event_id=61162bde007f8b289b2e0000&i=gh&m=ci)

## Stacktrace

    app/Services/Facebook.php:22 - App\Services\Facebook::postToPage
    app/Console/Commands/PostAvailablePharmacies.php:65 - App\Console\Commands\PostAvailablePharmacies::handle

[View full stacktrace](https://app.bugsnag.com/dodekatheon/farmakeia-dot-com-dot-cy/errors/61162bdea96a420007288215?event_id=61162bde007f8b289b2e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by gregkos** [comment]
Localization issue on the server, fixed.
